services:
  - type: web
    name: auth-service
    runtime: docker
    plan: free
    autoDeployTrigger: commit
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_ORIGINS
        value: http://localhost:3000,https://frontend-web-nine-theta.vercel.app
